# Generated by Django 5.1.6 on 2025-02-10 15:10

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=3, editable=False),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="item_embedding_hnsw_idx",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
