# Generated by Django 5.1.6 on 2025-02-10 16:11

import chat.validators
import django_lifecycle.mixins
import pgvector.django.halfvec
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_starbucksmenudocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxLawDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_content",
                    models.TextField(
                        validators=[
                            chat.validators.MaxTokenValidator("text-embedding-3-small")
                        ]
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "embedding",
                    pgvector.django.halfvec.HalfVectorField(
                        dimensions=3072, editable=False
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="taxlaw_doc_idx",
                        opclasses=["halfvec_cosine_ops"],
                    )
                ],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
